server:
  port: 8081
  
spring:
  h2:
    console:
      enabled: true
  cloud:
    stream:
      kafka:
        binder:
          brokers: localhost:9092
      bindings:
        multiplication_exchange:
          destination: multiplication_exchange
          content-type: application/json

  jpa:
    hibernate:
      ddl-auto: update
      
    properties:
      hibernate:
        show_sql:true       
    
  datasource:
    url: jdbc:h2:file:~/gamification
  
#multiplication:
#  exchange: multiplication_exchange
#  solved:
#    key: multiplication.solved
#  queue: gamification_multiplication_queue
#  anything:
#    routing-key: multiplication.* 
    
# REST client settings
multiplicationHost: http://localhost:8080